### ISSUE TITLE
notebooks\hello-npu return error

### ISSUE THREAD

**Issue by AlbertG123** [openvinotoolkit/openvino_notebooks#2167]
按着hello-npu.ipynb执行到compiled_model = core.compile_model(model, "NPU") 报错.

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[17], line 1
----> 1 compiled_model = core.compile_model(model, "NPU")

File [C:\Program](file:///C:/Program) Files\Python311\Lib\site-packages\openvino\runtime\ie_api.py:543, in Core.compile_model(self, model, device_name, config, weights)
    538     if device_name is None:
    539         return CompiledModel(
    540             super().compile_model(model, {} if config is None else config),
    541         )
    542     return CompiledModel(
--> 543         super().compile_model(model, device_name, {} if config is None else config),
    544     )
    545 else:
    546     if device_name is None:

RuntimeError: Exception from src/inference/src/cpp/core.cpp:107:
Exception from src/inference/src/dev/plugin.cpp:53:
Exception from src/plugins/intel_npu/src/plugin/src/plugin.cpp:662:
Exception from src/plugins/intel_npu/src/plugin/src/compiled_model.cpp:61:
Check 'result == ZE_RESULT_SUCCESS' failed at src/plugins/intel_npu/src/compiler/src/zero_compiler_in_driver.cpp:763:
Failed to compile network. L0 createGraph result: ZE_RESULT_ERROR_UNKNOWN, code 0x7ffffffe. Check 'false' failed at .[.\src\inference\src\core.cpp:104](http://localhost:8888/lab/tree/src/inference/src/core.cpp#line=103):
Check 'false' failed at .[.\src\frontends\common\src\frontend.cpp:54](http://localhost:8888/lab/tree/src/frontends/common/src/frontend.cpp#line=53):
Converting input model
Cannot create MaxPool layer aten::max_pool2d/MaxPool id:8 from unsupported opset: opset14

Failed to parse model info! Incorrect format!

**Comment by Wan-Intel** [comment]
Could you please share the hardware specification that you are using on your machine?

**Comment by AlbertG123** [comment]
Thinkpad T14p Gen2 - with Intel AI boost (NPU)
32G memory
1TB SSD
Intel GPU 16G
I think it's enough for converting with resnet50 model.
________________________________
From: Wan Wai Fook ***@***.***>
Sent: Sunday, July 7, 2024 6:16 PM
To: openvinotoolkit/openvino_notebooks ***@***.***>
Cc: Albert Gao ***@***.***>; Author ***@***.***>
Subject: [External] Re: [openvinotoolkit/openvino_notebooks] notebooks\hello-npu return error (Issue #2167)


Could you please share the hardware specification that you are using on your machine?

**Comment by eaidova** [comment]
@AlbertG123  which openvino version do you have?

**Comment by AlbertG123** [comment]
Hi, Aidova:
          following the Installing prerequisites<https://docs.openvino.ai/2022.3/notebooks-installation.html#installing-prerequisites>， Openvino>=2024.1.0 is installed which is documented in hello-npu.ipynb

________________________________
From: Ekaterina Aidova ***@***.***>
Sent: Monday, July 8, 2024 12:38 PM
To: openvinotoolkit/openvino_notebooks ***@***.***>
Cc: Albert Gao ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [openvinotoolkit/openvino_notebooks] notebooks\hello-npu return error (Issue #2167)


@AlbertG123<https://github.com/AlbertG123> which openvino version do you have?

**Comment by eaidova** [comment]
@AlbertG123  for double checking, could you please try to execute command in your virtual environment, where you run this notebook:
```
pip show openvino
pip show openvino-nightly
```
and provide results here?

**Comment by AlbertG123** [comment]
pip show openvino:
Name: openvino
Version: 2024.3.0.dev20240701
Summary: OpenVINO(TM) Runtime
Home-page: https://docs.openvino.ai/nightly/index.html
Author: Intel(R) Corporation
Author-email: ***@***.***
License: OSI Approved :: Apache Software License
Location: C:\Program Files\Python311\Lib\site-packages
Requires: numpy, openvino-telemetry, packaging
Required-by: openvino-tokenizers

pip show openvino-nightly:

WARNING: Package(s) not found: openvino-nightly



________________________________
From: Ekaterina Aidova ***@***.***>
Sent: Monday, July 8, 2024 5:35 PM
To: openvinotoolkit/openvino_notebooks ***@***.***>
Cc: Albert Gao ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [openvinotoolkit/openvino_notebooks] notebooks\hello-npu return error (Issue #2167)


@AlbertG123<https://github.com/AlbertG123> for double checking, could you please try to execute command in your virtual environment, where you run this notebook:

pip show openvino
pip show openvino-nightly
``

**Comment by AlbertG123** [comment]
Hi,
     latest status:

After change the command to :  compiled_model = core.compile_model(model,"AUTO")
It works. There is no error.
After change to : compiled_model = core.compile_model(model,"NPU")
There is error message:

RuntimeError: Exception from src/inference/src/cpp/core.cpp:107:
Exception from src/inference/src/dev/plugin.cpp:53:
Exception from src/plugins/intel_npu/src/plugin/src/plugin.cpp:662:
Exception from src/plugins/intel_npu/src/plugin/src/compiled_model.cpp:61:
Check 'result == ZE_RESULT_SUCCESS' failed at src/plugins/intel_npu/src/compiler/src/zero_compiler_in_driver.cpp:763:
Failed to compile network. L0 createGraph result: ZE_RESULT_ERROR_UNKNOWN, code 0x7ffffffe. Check 'false' failed at ..\src\inference\src\core.cpp:104<http://localhost:8888/src/inference/src/core.cpp#line=103>:
Check 'false' failed at ..\src\frontends\common\src\frontend.cpp:54<http://localhost:8888/src/frontends/common/src/frontend.cpp#line=53>:
Converting input model
Cannot create MaxPool layer aten::max_pool2d/MaxPool id:8 from unsupported opset: opset14
Failed to parse model info! Incorrect format!



And then following the notebooks ->
!benchmark_app -m compiled_model -d AUTO -hint throughput   < - this command can pass.  AUTO/ GPU/ CPU  ,these parameters can work.
!benchmark_app -m compiled_model -d NPU -hint throughput  <- after change to NPU, there is error:

Failed to compile network. L0 createGraph result: ZE_RESULT_ERROR_UNKNOWN, code 0x7ffffffe. Check 'false' failed at ..\src\inference\src\core.cpp:104:
Check 'false' failed at ..\src\frontends\common\src\frontend.cpp:54:
Converting input model
Cannot create MaxPool layer aten::max_pool2d/MaxPool id:9 from unsupported opset: opset14
Failed to parse model info! Incorrect format!


________________________________

**Comment by eaidova** [comment]
@AlbertG123 it looks like you installed development version of openvino that my be quit unstable. could you please reinstall it to 
`
pip install "openvino==2024.2.0"
`

AUTO device select another device (CPU or GPU) instead of NPU in your case and this error does not appear (supporting new introduced opset version may be added with delay for some specific platform, openvino downgrade to stable version should do not have such issue)

@dmatveev do you know something about plans for NPU to support MaxPool from opset14 or fallback to previous version for this op?

**Comment by eaidova** [comment]
@AlbertG123 the fix on openvino side was recently merged https://github.com/openvinotoolkit/openvino/pull/25467
Could you please try to upgrade openvino on the latest nightly:

```
pip install -U --pre openvino --extra-index-url --extra-index-url https://storage.openvinotoolkit.org/simple/wheels/nightly

**Comment by AlbertG123** [comment]
pip install -U -pre openvino --extra-index-url --extra-index-url https://storage.openvinotoolkit.org/simple/wheels/nightly
[AG] this command will return error ,  can't indentify what's the "-p" .
[AG] I change the command as below , and have a try
pip install -U openvino --extra-index-url https://storage.openvinotoolkit.org/simple/wheels/nightly

Looking in indexes: https://pypi.org/simple, https://storage.openvinotoolkit.org/simple/wheels/nightly
Requirement already satisfied: openvino in d:\source\intel_npu\rag\openvino_env\lib\site-packages (2024.2.0)
Requirement already satisfied: numpy<2.0.0,>=1.16.6 in d:\source\intel_npu\rag\openvino_env\lib\site-packages (from openvino) (1.26.4)
Requirement already satisfied: openvino-telemetry>=2023.2.1 in d:\source\intel_npu\rag\openvino_env\lib\site-packages (from openvino) (2024.1.0)
Requirement already satisfied: packaging in d:\source\intel_npu\rag\openvino_env\lib\site-packages (from openvino) (24.1)

**Comment by AlbertG123** [comment]
after change to NPU, got the same error:

 !benchmark_app -m {model_path} -d NPU -hint latency

...................
...................
RuntimeError: Exception from src/inference/src/cpp/core.cpp:107:
Exception from src/inference/src/dev/plugin.cpp:54:
Exception from src/plugins/intel_npu/src/plugin/src/plugin.cpp:622:
Exception from src/plugins/intel_npu/src/plugin/src/compiled_model.cpp:61:
Check 'result == ZE_RESULT_SUCCESS' failed at src/plugins/intel_npu/src/compiler/src/zero_compiler_in_driver.cpp:746:
Failed to compile network. L0 createGraph result: ZE_RESULT_ERROR_UNKNOWN, code 0x7ffffffe. Check 'false' failed at ..\src\inference\src\core.cpp:104:
Check 'false' failed at ..\src\frontends\common\src\frontend.cpp:54:
Converting input model
Cannot create MaxPool layer aten::max_pool2d/MaxPool id:9 from unsupported opset: opset14


Failed to parse model info! Incorrect format!

**Comment by eaidova** [comment]
@AlbertG123 
Sorry for wrong command, it should be:
```
pip install -U --pre openvino --extra-index-url --extra-index-url https://storage.openvinotoolkit.org/simple/wheels/nightly
```
using without --pre, lead to installing release version instead of development.
Did you reconvert model after reinstall openvino? Because previous generated IR with different openvino is not compatible with
 it

**Comment by AlbertG123** [comment]
Hi, Aidova :
         it can be successfully executed:
%pip install -U --pre openvino --extra-index-url https://storage.openvinotoolkit.org/simple/wheels/nightly


the log information as below
----------------------------------------------------------------------------------------------
Looking in indexes: https://pypi.org/simple, https://storage.openvinotoolkit.org/simple/wheels/nightly
Requirement already satisfied: openvino in c:\program files\python311\lib\site-packages (2024.3.0.dev20240701)
Collecting openvino
  Downloading https://storage.openvinotoolkit.org/wheels/nightly/openvino/openvino-2024.4.0.dev20240712-16028-cp311-cp311-win_amd64.whl (34.2 MB)

Requirement already satisfied: numpy<2.0.0,>=1.16.6 in c:\program files\python311\lib\site-packages (from openvino) (1.26.4) Requirement already satisfied: openvino-telemetry>=2023.2.1 in c:\program files\python311\lib\site-packages (from openvino) (2024.1.0) Requirement already satisfied: packaging in c:\program files\python311\lib\site-packages (from openvino) (24.1) Installing collected packages: openvino  Attempting uninstall: openvino    Found existing installation: openvino 2024.3.0.dev20240701    Uninstalling openvino-2024.3.0.dev20240701:      Successfully uninstalled openvino-2024.3.0.dev20240701 Successfully installed openvino-2024.4.0.dev20240712 Note: you may need to restart the kernel to use updated packages

--------------------------------------------------------------------------------------------------------------------------------------



  1.
After install new openvino with above command , I restart the jupyter notebooks
  2.
And run the jupyter notebooks step by step
  3.
Then got the same error as before.

              - compiled_model = core.compile_model(model,"NPU")    <--  there is no error,  after change NPU to AUTO,
Error logs:

------------------------------------------------------------------------------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[8], line 1
----> 1 compiled_model = core.compile_model(model,"NPU")

File C:\Program Files\Python311\Lib\site-packages\openvino\runtime\ie_api.py:543, in Core.compile_model(self, model, device_name, config, weights)
    538     if device_name is None:
    539         return CompiledModel(
    540             super().compile_model(model, {} if config is None else config),
    541         )
    542     return CompiledModel(
--> 543         super().compile_model(model, device_name, {} if config is None else config),
    544     )
    545 else:
    546     if device_name is None:


RuntimeError: Exception from src\inference\src\cpp\core.cpp:107:
Exception from src\inference\src\dev\plugin.cpp:53:
Exception from src\plugins\intel_npu\src\plugin\src\plugin.cpp:668:
Exception from src\plugins\intel_npu\src\plugin\src\compiled_model.cpp:61:
Check 'result == ZE_RESULT_SUCCESS' failed at src\plugins\intel_npu\src\compiler\src\zero_compiler_in_driver.cpp:811:
Failed to compile network. L0 createGraph result: ZE_RESULT_ERROR_UNKNOWN, code 0x7ffffffe. Check 'false' failed at ..\src\inference\src\core.cpp:104<http://localhost:8888/lab/workspaces/auto-c/tree/src/inference/src/core.cpp#line=103>:
Check 'false' failed at ..\src\frontends\common\src\frontend.cpp:54<http://localhost:8888/lab/workspaces/auto-c/tree/src/frontends/common/src/frontend.cpp#line=53>:
Converting input model
Cannot create MaxPool layer aten::max_pool2d/MaxPool id:8 from unsupported opset: opset14


Failed to parse model info! Incorrect format!

---------------------------------------------------------------------------------------------------





________________________________
From: Ekaterina Aidova ***@***.***>
Sent: Monday, July 15, 2024 12:34 PM
To: openvinotoolkit/openvino_notebooks ***@***.***>
Cc: Albert Gao ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [openvinotoolkit/openvino_notebooks] notebooks\hello-npu return error (Issue #2167)


@AlbertG123<https://github.com/AlbertG123>
Sorry for wrong command, it should be:

pip install -U --pre openvino --extra-index-url --extra-index-url https://storage.openvinotoolkit.org/simple/wheels/nightly


using without --pre, lead to installing release version instead of development.
Did you reconvert model after reinstall openvino? Because previous generated IR with different openvino is not compatible with
it

**Comment by eaidova** [comment]
@AlbertG123 what the result of running model on NPU with this package? Is it working?

**Comment by AlbertG123** [comment]
Hi,Aidova:     no, got the same error as before.

________________________________
From: Ekaterina Aidova ***@***.***>
Sent: Monday, July 15, 2024 7:50 PM
To: openvinotoolkit/openvino_notebooks ***@***.***>
Cc: Albert Gao ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [openvinotoolkit/openvino_notebooks] notebooks\hello-npu return error (Issue #2167)


@AlbertG123<https://github.com/AlbertG123> what the result of running model on NPU with this package? Is it working?

**Comment by AlbertG123** [comment]
No, it's not working.
There still error when : compiled_model = core.compile_model(model,"NPU")

RuntimeError                              Traceback (most recent call last) Cell In[8], line 1 ----> 1 compiled_model = core.compile_model(model,"NPU")
.............
________________________________
From: Ekaterina Aidova ***@***.***>
Sent: Monday, July 15, 2024 7:50 PM
To: openvinotoolkit/openvino_notebooks ***@***.***>
Cc: Albert Gao ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [openvinotoolkit/openvino_notebooks] notebooks\hello-npu return error (Issue #2167)


@AlbertG123<https://github.com/AlbertG123> what the result of running model on NPU with this package? Is it working?

**Comment by AlbertG123** [comment]
hi, Intel team:
                    any comments ? thanks for your great help

**Comment by avitial** [comment]
@AlbertG123 sorry for the delay, I was able to reproduce the issue you have reported. It's unclear what the issue is caused by, whether the NPU plugin or the NPU driver or the model conversion itself on the latest release (as model converted with 2024.1 version can run normally with 2024.3 runtime). We have captured this as a bug and will share updates as they become available.

As possible workarounds try one of the following options (recommend option number 1):
1. Try using OpenVINO 2024.1 to run the notebook. Make sure to clean the environment, especially the contents of the `model` folder, as model needs to be converted using 2024.1 version. 
2. Modify the contents of the already generated IR model file (_.xml_), look for the _aten::max_pool2d/MaxPool_ layer and change version from _opset14_ to use _opset8_:

```
                # from:
                <layer id="8" name="aten::max_pool2d/MaxPool" type="MaxPool" version="opset14">
                # to:
                <layer id="8" name="aten::max_pool2d/MaxPool" type="MaxPool" version="opset8">
```


Ref. 148879

**Comment by frenchwr** [comment]
Hello, I hit this error as well while walking through [the hello-npu notebook](https://github.com/openvinotoolkit/openvino_notebooks/blob/ac3b192073ac553e16d1f7e4f3df46e9081653dd/notebooks/hello-npu/hello-npu.ipynb) using OpenVINO 2024.3.0, and wanted to share that the second suggested workaround (changing `version="opset14"` to `version="opset8"`)  worked for me. I did not attempt the first suggested workaround.

**Comment by AlbertG123** [comment]
OK. I will try it later
________________________________
From: Will French ***@***.***>
Sent: Tuesday, August 20, 2024 10:44 PM
To: openvinotoolkit/openvino_notebooks ***@***.***>
Cc: Albert Gao ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [openvinotoolkit/openvino_notebooks] notebooks\hello-npu return error (Issue #2167)


Hello, I hit this error as well while walking through the hello-npu notebook<https://github.com/openvinotoolkit/openvino_notebooks/blob/ac3b192073ac553e16d1f7e4f3df46e9081653dd/notebooks/hello-npu/hello-npu.ipynb> using OpenVINO 2024.3.0, and wanted to share that the second suggested workaround (changing version="opset14" to version="opset8") worked for me. I did not attempt the first suggested workaround.

**Comment by lyh007** [comment]
我也遇到了相同问题，如何解决？
  File "D:\dev\appserver\python\anaconda3\envs\langchain\lib\site-packages\optimum\intel\openvino\modeling_base.py", line 527, in compile
    self.request = core.compile_model(self.model, self._device, ov_config)
  File "D:\dev\appserver\python\anaconda3\envs\langchain\lib\site-packages\openvino\runtime\ie_api.py", line 543, in compile_model
    super().compile_model(model, device_name, {} if config is None else config),
RuntimeError: Exception from src\inference\src\cpp\core.cpp:107:
Exception from src\inference\src\dev\plugin.cpp:53:
Exception from src\plugins\intel_npu\src\plugin\src\plugin.cpp:674:
Exception from src\plugins\intel_npu\src\plugin\src\compiled_model.cpp:61:
Exception from src\core\src\partial_shape.cpp:266:
to_shape was called on a dynamic shape.
环境信息：
(langchain) C:\Windows\System32>pip show openvino
Name: openvino
Version: 2024.3.0
Summary: OpenVINO(TM) Runtime
Home-page: https://docs.openvino.ai/2023.0/index.html
Author: Intel(R) Corporation
Author-email: openvino@intel.com
License: OSI Approved :: Apache Software License
Location: d:\dev\appserver\python\anaconda3\envs\langchain\lib\site-packages
Requires: numpy, openvino-telemetry, packaging
Required-by: openvino-tokenizers

**Comment by brmarkus** [comment]
> Exception from src\core\src\partial_shape.cpp:266: to_shape was called on a dynamic shape.

Have a look under "https://docs.openvino.ai/2024/openvino-workflow/running-inference/inference-devices-and-modes/npu-device.html#limitations". At least currently, for the NPU only static shapes are supported.

See also "https://docs.openvino.ai/2024/openvino-workflow/running-inference/inference-devices-and-modes/gpu-device.html#dynamic-shapes" for the GPU plugin: "Currently, dynamic shape support for GPU is a preview feature and has the following limitations"

**Comment by brmarkus** [comment]
> Hello, I hit this error as well while walking through [the hello-npu notebook](https://github.com/openvinotoolkit/openvino_notebooks/blob/ac3b192073ac553e16d1f7e4f3df46e9081653dd/notebooks/hello-npu/hello-npu.ipynb) using OpenVINO 2024.3.0, and wanted to share that the second suggested workaround (changing `version="opset14"` to `version="opset8"`) worked for me. I did not attempt the first suggested workaround.

@raymondlo84 would your just submitted workaround be required in other notebooks like this?

**Comment by raymondlo84** [comment]
> > Hello, I hit this error as well while walking through [the hello-npu notebook](https://github.com/openvinotoolkit/openvino_notebooks/blob/ac3b192073ac553e16d1f7e4f3df46e9081653dd/notebooks/hello-npu/hello-npu.ipynb) using OpenVINO 2024.3.0, and wanted to share that the second suggested workaround (changing `version="opset14"` to `version="opset8"`) worked for me. I did not attempt the first suggested workaround.
> 
> @raymondlo84 would your just submitted workaround be required in other notebooks like this?

I found the same error in YOLOv8 demo, and same workaround can fix that too.

**Comment by AlbertG123** [comment]
second workaround also works on my system. thank you all.
